AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A Step Functions Workflow for invoking LLM Model on Amazon Bedrock

Parameters:
  ModelId:
    Type: String
    Default: arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-v2
    Description: Enter the arn of the model that you would like to invoke
  
Resources:
##########################################################################
#   STEP FUNCTION                                                        #
##########################################################################

  StateMachineInvokeBedrock:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/StateMachine.asl.json
      DefinitionSubstitutions:
        InvokeBedrock: !Ref InvokeBedrock
      Type: STANDARD
      Policies:
        - InvokeModelPolicy:
            Arn: !Ref ModelId


##########################################################################
#  Bedrock                                                            #
##########################################################################
  InvokeBedrock:
    Type: AWS::SNS::Topic
    Properties:
      ModelId: !Ref ModelId
            
##########################################################################
#   Outputs                                                              #
##########################################################################
Outputs:
