AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A Step Functions Workflow for invoking LLM Model on Amazon Bedrock

Parameters:
  ModelId:
    Type: String
    Default: arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-v2
    Description: Enter the arn of the model that you would like to invoke
  
Resources:
##########################################################################
#   STEP FUNCTION                                                        #
##########################################################################

  StateMachineBedrockInvoke:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/StateMachine.asl.json
      Type: STANDARD
            
##########################################################################
#   Outputs                                                              #
##########################################################################
Outputs:
